// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/kitoyanok66/workk/config"
	"github.com/kitoyanok66/workk/internal/auth"
	"github.com/kitoyanok66/workk/internal/db"
	"github.com/kitoyanok66/workk/internal/freelancers"
	"github.com/kitoyanok66/workk/internal/likes"
	"github.com/kitoyanok66/workk/internal/matches"
	"github.com/kitoyanok66/workk/internal/middleware"
	"github.com/kitoyanok66/workk/internal/projects"
	"github.com/kitoyanok66/workk/internal/skills"
	"github.com/kitoyanok66/workk/internal/users"
	"gorm.io/gorm"
	"time"
)

// Injectors from wire.go:

func InitApp(cfg *config.Config) (*App, error) {
	gormDB, err := db.InitDB(cfg)
	if err != nil {
		return nil, err
	}
	userRepository := users.NewUserRepository(gormDB)
	userService := users.NewUserService(userRepository)
	skillRepository := skills.NewSkillRepository(gormDB)
	skillService := skills.NewSkillService(skillRepository)
	projectRepository := projects.NewProjectRepository(gormDB)
	projectService := projects.NewProjectService(projectRepository, skillService, userService)
	freelancerRepository := freelancers.NewFreelancerRepository(gormDB)
	freelancerService := freelancers.NewFreelancerService(freelancerRepository, skillService, userService)
	likeRepository := likes.NewLikeRepository(gormDB)
	matchRepository := matches.NewMatchRepository(gormDB)
	matchService := matches.NewMatchService(matchRepository)
	likeService := likes.NewLikeService(likeRepository, userService, matchService)
	authRepository := auth.NewAuthRepository(gormDB)
	authService := auth.NewAuthService(authRepository, userService)
	string2 := provideJWTSecret(cfg)
	duration := provideJWTTTL(cfg)
	jwtManager := middleware.NewJWTManager(string2, duration)
	app := NewApp(gormDB, userService, skillService, projectService, freelancerService, likeService, matchService, authService, jwtManager)
	return app, nil
}

// wire.go:

type App struct {
	DB                *gorm.DB
	JWTManager        *middleware.JWTManager
	UserService       users.UserService
	SkillService      skills.SkillService
	ProjectService    projects.ProjectService
	FreelancerService freelancers.FreelancerService
	LikeService       likes.LikeService
	MatchService      matches.MatchService
	AuthService       auth.AuthService
}

func provideJWTSecret(cfg *config.Config) string {
	return cfg.JWTSecret
}

func provideJWTTTL(cfg *config.Config) time.Duration {
	return cfg.JWTTTLHours
}

func NewApp(db2 *gorm.DB,
	userSvc users.UserService,
	skillSvc skills.SkillService,
	projectSvc projects.ProjectService,
	freelancerSvc freelancers.FreelancerService,
	likeSvc likes.LikeService,
	matchSvc matches.MatchService,
	authSvc auth.AuthService,
	jwtManager *middleware.JWTManager,
) *App {
	fAdapter := freelancers.NewFreelancerFetcherAdapter(freelancerSvc)
	pAdapter := projects.NewProjectFetcherAdapter(projectSvc)
	lAdapter := likes.NewLikeFetcherAdapter(likeSvc)

	freelancerSvc.SetProjectDep(pAdapter)
	freelancerSvc.SetLikeDep(lAdapter)

	projectSvc.SetFreelancerDep(fAdapter)
	projectSvc.SetLikeDep(lAdapter)

	likeSvc.SetFreelancerDep(fAdapter)
	likeSvc.SetProjectDep(pAdapter)

	return &App{
		DB:                db2,
		UserService:       userSvc,
		SkillService:      skillSvc,
		ProjectService:    projectSvc,
		FreelancerService: freelancerSvc,
		LikeService:       likeSvc,
		MatchService:      matchSvc,
		AuthService:       authSvc,
		JWTManager:        jwtManager,
	}
}
